# Generated by Django 5.1.1 on 2024-10-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_en_us",
                    models.CharField(max_length=200, verbose_name="question"),
                ),
                (
                    "question_ru",
                    models.CharField(max_length=200, verbose_name="question"),
                ),
                (
                    "question_de",
                    models.CharField(max_length=200, verbose_name="question"),
                ),
                (
                    "answer_en_us",
                    models.CharField(max_length=200, verbose_name="answer"),
                ),
                ("answer_ru", models.CharField(max_length=200, verbose_name="answer")),
                ("answer_de", models.CharField(max_length=200, verbose_name="answer")),
                (
                    "required_field",
                    models.CharField(max_length=200, verbose_name="any_char_field"),
                ),
                (
                    "default_field",
                    models.IntegerField(default=10, verbose_name="any_int_field"),
                ),
            ],
        ),
    ]
