# Generated by Django 5.1.1 on 2024-11-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_320x240",
                    models.ImageField(upload_to="photo/", verbose_name="photo"),
                ),
                (
                    "photo_320x480",
                    models.ImageField(upload_to="photo/", verbose_name="photo"),
                ),
                (
                    "photo_800x600",
                    models.ImageField(upload_to="photo/", verbose_name="photo"),
                ),
            ],
        ),
    ]
