name: tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: tests
    steps:
      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Установка Poetry
        uses: snok/install-poetry@v1
        with:
          poetry-version: 1.5.0

      - name: Извлечение репозитория
        uses: actions/checkout@v4

      - name: Установка зависимостей
        run: poetry install
      - name: Запуск тестов
        env:
          DEEPL_TRANSLATOR_KEY: ${{ secrets.DEEPL_TRANSLATOR_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: poetry run pytest